### ISSUE TITLE
Home Page Issues 

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#103]
- [x] Add time effect to the banner

- [x] Ensure aspect ratios for the banner images is correct

- [x] Add captions for the images - **Kolo to send these**

- [x]  Adding Icons for the columns - **Kolo to send this**

- [x] 1st  Column  -  Have less  text and  more news I t ems -  **Kolo  to provide blurbs** 

- [x] 2nd Column - Add 2 - 3 resource links with blurbs - Social media, Digital parenting, Audio Visual etc

- [x] 3rd column - Remove current text and have and add parenting tips listed down with their titles

- [x] Add WHO and UNICEF digital campaind

**Comment by Patowhiz** [comment]
@maxwellfundi I can add the time effect and structure the captions. The rest it's just about filling the content cause we have the structure in place. You will just look at how the new content will fit in the structure. I think no extra css will be needed. If it's needed I will just add it.

**Comment by Patowhiz** [comment]
@maxwellfundi we now have the timer effect on the banner and the captions. The banner images just need to be supplied with width of 1040px and height of 400px.

**Comment by Patowhiz** [comment]
The colour of the caption that we use is heavily depended on the images used in the a banner.
