### ISSUE TITLE
Tips page issues

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#105]
- [x] Change the thumbnails for the tipsheets to list. Have only one thumbnail. 

- [x] Play around and report what works well for this

**Comment by Patowhiz** [comment]
@maxwellfundi  You mean have them arranged into columns? Like they mobile view?

**Comment by Patowhiz** [comment]
@maxwellfundi this is now done. Will be similar to the caseworkers tipsheets design.
I haven't managed to include the thumbnail because each thumbnail is specific to the tipsheet and are not related. I didn't see how we could do that while at the same retaining the consistency of the links.
