### ISSUE TITLE
Caseworkers page 

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#106]
- [x] Add - _Tips for caseworkers are available in_  then list the languages **Alphabetically**

- [x] Insert a snapshot of the tips for caseworkers to have a general idea of how they look like

**Comment by Patowhiz** [comment]
@maxwellfundi i forgot to ask about item 2. Here the snapshot needs to be added yet in the tipsheet, the snapshot needs to be removed?
