### ISSUE TITLE
Current News menu 

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#112]
- [x] create a page similar to resources with links to News, Newsletters, webinars

- [x] News top be renamed - **Kolo to give us the name** we can implement with dummy name for now

- [x] Add images for the news, with blurbs and read more buttons @maxwellfundi  **to revert on how this goes down**

**Comment by maxwellfundi** [comment]
@maxwellfundi  create new component for news page! Paste resources formnat

**Comment by Patowhiz** [comment]
@maxwellfundi  I have made the changes to the News component. The blurbs supplied just need to have a height of 150px.
