### ISSUE TITLE
Webinars page 

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#114]
- [x] Shorter blurbs for the videos - **Kolo to provide**

- [x] Change  Read more  to Watch on youtube - to open a youtube channel

**Comment by Patowhiz** [comment]
@maxwellfundi those are not blurbs. They are video screenshots that are supposed to come from youtube. Once the correct embedded link are set. They will have the correct screenshots. So in the iframe. We just need to change the `src` attribute value.

**Comment by maxwellfundi** [comment]
Yes i understand, I mean the text besides the videos.

**Comment by maxwellfundi** [comment]
Yes i understand, I mean the text besides the videos.

**Comment by Patowhiz** [comment]
@maxwellfundi get my new changes before making changes to the iframe `src `attribute value.

**Comment by maxwellfundi** [comment]
@Patowhiz  okay no worries. I am now getting down to work. Am pulling these.
