### ISSUE TITLE
Contibutors Page Issues 

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#115]
- [x] Contributors page- Have sections with alphabets, when clicked they show the names within the range of alphabets

**Comment by Patowhiz** [comment]
@maxwellfundi this requires a functionality change

**Comment by maxwellfundi** [comment]
So what do you  think we can do quickly?

**Comment by Patowhiz** [comment]
@maxwellfundi I've made the design and functionality change.
