### ISSUE TITLE
Impact page 

### ISSUE THREAD

**Issue by maxwellfundi** [IDEMSInternational/covid-parenting-website#116]
- [x] The statistics to appear on top of the maps

- [x] global map to start on the top left

- [x] Alternate maps- blue, dark blue ....

- [x] Aspect ratio needs to be checked

- [x] Dissemination - Add icons for these - **Kolo to provide them**

- [x] Arrange the dissemination well in a presentable way with icons

- [x] Add % on the numbers on dissemiantion

- [x] Use the conservative numbers on the excel sheet

**Comment by Patowhiz** [comment]
@maxwellfundi 
Do we have the dark blue maps?
Should we also add % on the maps?
By conservative numbers, do you mean the minimum?

**Comment by Patowhiz** [comment]
Oh! I've seen what you mean by alternating the maps.

**Comment by Patowhiz** [comment]
And the conservative percentage numbers for the maps don't add up to 100%

**Comment by Patowhiz** [comment]
I have made the above changes. The aspect ratio is depended on supplied images and resizing. I will look into this since it's more of a design problem.

**Comment by maxwellfundi** [comment]
okay great. So if we can have an ask by the end of the day about the images and dimensions that would be great then I am on hompage images now

**Comment by Patowhiz** [comment]
Yes. Just look at the all the current image sizes. Then ask for them in an already resized size. Then the only thing that will be needed is replacing them with the current ones.
